#
# version.cmake : version du projet
#

set (MAGIX3D_MAJOR_VERSION "2")
set (MAGIX3D_MINOR_VERSION "2")
set (MAGIX3D_RELEASE_VERSION "5")
set (MAGIX3D_VERSION ${MAGIX3D_MAJOR_VERSION}.${MAGIX3D_MINOR_VERSION}.${MAGIX3D_RELEASE_VERSION})

set (MAGIX3D_CORBA_API_MAJOR_VERSION "0")
set (MAGIX3D_CORBA_API_MINOR_VERSION "1")
set (MAGIX3D_CORBA_API_RELEASE_VERSION "0")
set (MAGIX3D_CORBA_API_VERSION ${MAGIX3D_CORBA_API_MAJOR_VERSION}.${MAGIX3D_CORBA_API_MINOR_VERSION}.${MAGIX3D_CORBA_API_RELEASE_VERSION})

