#
# version.cmake : version du projet
#

set (MAGIX3D_MAJOR_VERSION "2")
set (MAGIX3D_MINOR_VERSION "6")
set (MAGIX3D_RELEASE_VERSION "2")
set (MAGIX3D_VERSION ${MAGIX3D_MAJOR_VERSION}.${MAGIX3D_MINOR_VERSION}.${MAGIX3D_RELEASE_VERSION})

